using System.Reflection;
using MMCA.Common.Domain.Attributes;

namespace MMCA.Common.Domain.Extensions;

/// <summary>
/// Extension type adding domain-attribute inspection capabilities to <see cref="Type"/>.
/// </summary>
public static class EntityTypeExtensions
{
    extension(Type entityType)
    {
        /// <summary>
        /// Gets a value indicating whether this entity type is decorated with
        /// <see cref="IdValueGeneratedAttribute"/>, meaning its ID is auto-generated by
        /// the database (e.g., SQL Server IDENTITY). Factory methods use this at runtime
        /// to decide whether to assign an explicit ID or use <see langword="default"/>.
        /// </summary>
        public bool IsIdValueGenerated => entityType.GetCustomAttribute<IdValueGeneratedAttribute>() is not null;
    }
}
