using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;
using MMCA.Common.Application.Interfaces.Events;
using MMCA.Common.Application.Interfaces.Infrastructure.Persistence;
using MMCA.Common.Domain.Attributes;
using MMCA.Common.Domain.Entities;
using MMCA.Common.Infrastructure.Persistence.DataSources;
using MMCA.Common.Infrastructure.Persistence.DbContexts;
using MMCA.Common.Infrastructure.Persistence.Interceptors;
using MMCA.Common.Infrastructure.Persistence.Outbox.Processing;
using MMCA.Common.Infrastructure.Tests.TestDoubles;
using MMCA.Common.Shared.Identifiers;
using Moq;

namespace MMCA.Common.Infrastructure.Tests.Persistence.Conversions;

/// <summary>The canonical two-line identifier declaration, over an int key generated by the store.</summary>
public readonly record struct OrderId(int Value) : IStronglyTypedId<OrderId, int>
{
    /// <summary>Wraps a primitive order key.</summary>
    public static OrderId From(int value) => new(value);
}

/// <summary>A second int-backed identifier, held by an entity that does not own it.</summary>
public readonly record struct CustomerId(int Value) : IStronglyTypedId<CustomerId, int>
{
    /// <summary>Wraps a primitive customer key.</summary>
    public static CustomerId From(int value) => new(value);
}

/// <summary>A Guid-backed identifier, the shape an externally-issued key takes.</summary>
public readonly record struct SpeakerId(Guid Value) : IStronglyTypedId<SpeakerId, Guid>
{
    /// <summary>Wraps a speaker key.</summary>
    public static SpeakerId From(Guid value) => new(value);
}

/// <summary>A long-backed identifier, used here in its optional (<c>LineId?</c>) form.</summary>
public readonly record struct LineId(long Value) : IStronglyTypedId<LineId, long>
{
    /// <summary>Wraps a primitive line key.</summary>
    public static LineId From(long value) => new(value);
}

/// <summary>An aggregate root keyed by a wrapper whose value the database generates.</summary>
[IdValueGenerated]
public sealed class WrappedOrder : AuditableAggregateRootEntity<OrderId>
{
    public string Code { get; set; } = string.Empty;

    public CustomerId CustomerId { get; set; }
}

/// <summary>An entity keyed by an application-assigned wrapper, holding an optional wrapper too.</summary>
public sealed class WrappedSpeaker : AuditableBaseEntity<SpeakerId>
{
    public string DisplayName { get; set; } = string.Empty;

    public LineId? SessionId { get; set; }
}

/// <summary>
/// A real SQLite database over entities keyed by strongly typed identifiers, built the way
/// <c>AuditTrailTestContext</c> is: the production <see cref="ApplicationDbContext"/> base, so the
/// pre-convention registration under test is the one production runs, with the entity mapping
/// declared inline rather than discovered.
/// </summary>
public sealed class WrappedIdSqliteContext : ApplicationDbContext
{
    private WrappedIdSqliteContext(DbContextOptions<WrappedIdSqliteContext> options, IServiceProvider serviceProvider)
        : base(options, serviceProvider, new WrappedIdContextServices.NoAssemblies(), TestPhysicalDataSources.Sqlite())
    {
    }

    public DbSet<WrappedOrder> Orders => Set<WrappedOrder>();

    public DbSet<WrappedSpeaker> Speakers => Set<WrappedSpeaker>();

    internal override bool SupportsOutbox => false;

    /// <summary>Creates the context over a fresh in-memory database.</summary>
    /// <returns>An open context whose schema has been created.</returns>
    public static WrappedIdSqliteContext Create()
    {
        var options = new DbContextOptionsBuilder<WrappedIdSqliteContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;

        var context = new WrappedIdSqliteContext(options, WrappedIdContextServices.Create(withRegistry: true));
        context.Database.OpenConnection();
        context.Database.EnsureCreated();
        return context;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => WrappedIdContextServices.MapEntities(modelBuilder);
}

/// <summary>
/// The same entities on a context built WITHOUT the identifier registry, so the model reaches EF's
/// own "the database provider does not support this type" validation. A context class of its own
/// because EF caches one model per (context type, physical source name).
/// </summary>
public sealed class WrappedIdBareSqliteContext : ApplicationDbContext
{
    private WrappedIdBareSqliteContext(DbContextOptions<WrappedIdBareSqliteContext> options, IServiceProvider serviceProvider)
        : base(options, serviceProvider, new WrappedIdContextServices.NoAssemblies(), TestPhysicalDataSources.Sqlite())
    {
    }

    internal override bool SupportsOutbox => false;

    /// <summary>Creates the context. Reading its model is what throws.</summary>
    /// <returns>The context.</returns>
    public static WrappedIdBareSqliteContext Create()
    {
        var options = new DbContextOptionsBuilder<WrappedIdBareSqliteContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;

        return new WrappedIdBareSqliteContext(options, WrappedIdContextServices.Create(withRegistry: false));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => WrappedIdContextServices.MapEntities(modelBuilder);
}

/// <summary>The same entities on the SQL Server provider, for the model assertions. Never connects.</summary>
public sealed class WrappedIdSqlServerContext : ApplicationDbContext
{
    private WrappedIdSqlServerContext(DbContextOptions<WrappedIdSqlServerContext> options, IServiceProvider serviceProvider)
        : base(options, serviceProvider, new WrappedIdContextServices.NoAssemblies(), TestPhysicalDataSources.SqlServer())
    {
    }

    internal override bool SupportsOutbox => false;

    /// <summary>Creates the context over an unreachable connection string; only its model is read.</summary>
    /// <returns>The context.</returns>
    public static WrappedIdSqlServerContext Create()
    {
        var options = new DbContextOptionsBuilder<WrappedIdSqlServerContext>()
            .UseSqlServer("Server=unused;Database=unused;")
            .Options;

        return new WrappedIdSqlServerContext(options, WrappedIdContextServices.Create(withRegistry: true));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => WrappedIdContextServices.MapEntities(modelBuilder);
}

/// <summary>The same entities on the PostgreSQL provider, for the model assertions. Never connects.</summary>
public sealed class WrappedIdPostgresContext : ApplicationDbContext
{
    private WrappedIdPostgresContext(DbContextOptions<WrappedIdPostgresContext> options, IServiceProvider serviceProvider)
        : base(options, serviceProvider, new WrappedIdContextServices.NoAssemblies(), TestPhysicalDataSources.Postgres())
    {
    }

    internal override bool SupportsOutbox => false;

    /// <summary>Creates the context over an unreachable connection string; only its model is read.</summary>
    /// <returns>The context.</returns>
    public static WrappedIdPostgresContext Create()
    {
        var options = new DbContextOptionsBuilder<WrappedIdPostgresContext>()
            .UseNpgsql("Host=localhost;Database=unused;Username=app")
            .Options;

        return new WrappedIdPostgresContext(options, WrappedIdContextServices.Create(withRegistry: true));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => WrappedIdContextServices.MapEntities(modelBuilder);
}

/// <summary>
/// Shared scaffolding for the four wrapped-identifier contexts: the service provider each one needs
/// and the entity mapping they share.
/// <para>
/// The entities are mapped inline rather than through discovered
/// <c>EntityTypeConfiguration</c> classes on purpose. A discovered configuration is visible to every
/// OTHER test in this assembly that points an assembly provider at it, and an entity keyed by a
/// wrapper would then land in models whose context was never given the identifier registry.
/// </para>
/// </summary>
internal static class WrappedIdContextServices
{
    /// <summary>Builds the service provider an <c>ApplicationDbContext</c> subclass needs here.</summary>
    /// <param name="withRegistry">Whether to opt the context into strongly typed identifiers.</param>
    /// <returns>The service provider.</returns>
    public static IServiceProvider Create(bool withRegistry)
    {
        var services = new ServiceCollection();
        services.AddSingleton(new AuditSaveChangesInterceptor(TimeProvider.System));
        services.AddSingleton(_ => new DomainEventSaveChangesInterceptor(
            Mock.Of<IDomainEventDispatcher>(),
            NullLogger<DomainEventSaveChangesInterceptor>.Instance,
            Mock.Of<IOutboxSignal>()));
        services.AddSingleton<IEntityDataSourceRegistry>(new EmptyEntityDataSourceRegistry());

        if (withRegistry)
        {
            services.AddSingleton(new StronglyTypedIdRegistry(
                [typeof(OrderId), typeof(CustomerId), typeof(SpeakerId), typeof(LineId)]));
        }

        return services.BuildServiceProvider();
    }

    /// <summary>Maps the two wrapped-identifier entities.</summary>
    /// <param name="modelBuilder">The model builder.</param>
    public static void MapEntities(ModelBuilder modelBuilder)
    {
        ArgumentNullException.ThrowIfNull(modelBuilder);

        modelBuilder.Entity<WrappedOrder>(entity =>
        {
            entity.ToTable("WrappedOrders");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Ignore(e => e.DomainEvents);
        });

        modelBuilder.Entity<WrappedSpeaker>(entity =>
        {
            entity.ToTable("WrappedSpeakers");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
        });
    }

    /// <summary>An assembly provider that discovers nothing, so no configuration is swept in.</summary>
    internal sealed class NoAssemblies : IEntityConfigurationAssemblyProvider
    {
        public IReadOnlyList<Assembly> GetConfigurationAssemblies() => [];
    }
}
