using System.Globalization;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using Microsoft.IdentityModel.Tokens;

namespace MMCA.Common.Testing;

/// <summary>
/// Generates JWT tokens for integration tests. Each downstream project extends this with
/// role-specific convenience methods (e.g., AdminToken, OrganizerToken).
/// <para>
/// Tokens are signed with <b>RS256</b> (RSA-SHA256) using the embedded dev keypair
/// (<see cref="DefaultPublicKeyPem"/> / the paired private key). This matches the
/// production signing algorithm configured by <c>AddCommonAuthentication</c> in MMCA.Common,
/// so integration tests exercise the same JWKS/RS256 validation code path that production runs.
/// Test host appsettings must set <c>Jwt:SigningAlgorithm=RS256</c>,
/// <c>Jwt:RsaPublicKeyPem=&lt;DefaultPublicKeyPem&gt;</c>, and
/// <c>Jwks:KeyId=&lt;DefaultKeyId&gt;</c> for token validation to succeed.
/// </para>
/// <para>
/// ⚠ <b>Security note:</b> the embedded RSA keypair is committed to the public git repo and is
/// therefore insecure by design — it exists solely to make integration tests deterministic
/// without a per-run key-generation step. Never configure a production deployment with this
/// keypair. Production keys are provisioned via user-secrets / Azure Key Vault per
/// <c>JwtSettings.RsaPrivateKeyPem</c>.
/// </para>
/// </summary>
public static class JwtTokenGenerator
{
    /// <summary>Default test issuer, matching the <c>Jwt:Issuer</c> configured in test appsettings.</summary>
    public const string DefaultIssuer = "https://localhost:6001";

    /// <summary>
    /// Key identifier (<c>kid</c>) embedded in the JWT header and advertised on the JWKS document
    /// generated by <see cref="DefaultPublicKeyPem"/>. Test host appsettings set
    /// <c>Jwks:KeyId</c> to this value so <c>RsaJwksProvider</c> publishes a JWKS entry with the
    /// matching <c>kid</c>.
    /// </summary>
    public const string DefaultKeyId = "mmca-test-key";

    /// <summary>
    /// PEM-encoded RSA-2048 PUBLIC key paired with the private key used for signing tokens.
    /// Expose this to test host appsettings via <c>Jwt:RsaPublicKeyPem</c> /
    /// <c>Jwks:RsaPublicKeyPem</c> so the host validates signatures against the same key that
    /// <see cref="GenerateToken"/> signs with.
    /// </summary>
    public const string DefaultPublicKeyPem =
        "-----BEGIN PUBLIC KEY-----\n" +
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnnbSkwyzrgJ7cs+wlLrq\n" +
        "akfrCvbOIiDM4+AtwLfRT7ImZkJAQYK+dDRU8SXdZ1Uy9sPj1yvBshFfAKOYf2b0\n" +
        "rEcjZvU/JnieRecNDYkuecq7splXsxrRdKBv9y1lRMgQcu1Nox8rmEDERLEgExLp\n" +
        "V4yT3s9GKPFolP+aV7RJtV5YmWGBjPSnzAoykiYlKCwxEjRVVqjTQx/Z7IKxWlDF\n" +
        "+lzlr/XnmDCie4G5tihhF+QEvyNBl5e3LQs5/fGfO/e2FI7FX1weNNr1/kPXVcJ9\n" +
        "lOakfvLpvaWYGYY7I90KBfHs2vqBvwKjhyE/aRiDpQy3FNYB5BkfJrtUWulBjYd4\n" +
        "jQIDAQAB\n" +
        "-----END PUBLIC KEY-----";

    /// <summary>
    /// PEM-encoded RSA-2048 PRIVATE key used to sign test tokens. Exposed as public so test
    /// host configuration (e.g., <c>TestWebApplicationFactory</c> injecting
    /// <c>Jwt:RsaPrivateKeyPem</c>) can reference it — required because <c>JwtSettings.Validate</c>
    /// insists on a non-empty private key when <c>SigningAlgorithm=RS256</c>. See the class
    /// remarks for the security warning — this key is for test use only. The key material is
    /// already publicly visible in git history regardless of C# access modifier.
    /// </summary>
    public const string DefaultPrivateKeyPem =
        "-----BEGIN PRIVATE KEY-----\n" +
        "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCedtKTDLOuAnty\n" +
        "z7CUuupqR+sK9s4iIMzj4C3At9FPsiZmQkBBgr50NFTxJd1nVTL2w+PXK8GyEV8A\n" +
        "o5h/ZvSsRyNm9T8meJ5F5w0NiS55yruymVezGtF0oG/3LWVEyBBy7U2jHyuYQMRE\n" +
        "sSATEulXjJPez0Yo8WiU/5pXtEm1XliZYYGM9KfMCjKSJiUoLDESNFVWqNNDH9ns\n" +
        "grFaUMX6XOWv9eeYMKJ7gbm2KGEX5AS/I0GXl7ctCzn98Z8797YUjsVfXB402vX+\n" +
        "Q9dVwn2U5qR+8um9pZgZhjsj3QoF8eza+oG/AqOHIT9pGIOlDLcU1gHkGR8mu1Ra\n" +
        "6UGNh3iNAgMBAAECggEAJ3pEtZu5e8VkidLSFAuI8Ndf6AhajEgNo0urOlLRE4C3\n" +
        "bkxdA7UVy49qBfW/9clU/AMLVQSyqbEIMPmQuVSl6fGDEVhR1jzAeXu5VcDyUic+\n" +
        "oZzwK0+oFN0PZ83oZ71L08XozJWsX67q9o4GBpp0hXohMKYEvZh+zHftNKJWppco\n" +
        "1G6Lto3ELzlShhbOosoNce1Y8jByY2cc617MO1S/I6tB3NPsiZMRKgC/j3ATWimD\n" +
        "x9ElTIc3lsT+aopol95pkGsIvfh3tCXeaUuCZ+rWEX4xtVtPpm+f1hjDxZcGHwL4\n" +
        "DxGZKtTAmkbA9u2beMEhtCYE6fwVKDzD/K4ZF8HzYQKBgQDbZD9t7i3EYTuF4Ej2\n" +
        "LoDeRIG1g7eXBcHqWWeBZnQa/fqlFnzqkphVOKxzVB9s9HDK0Ku3khe9wJI5XHFx\n" +
        "tDWUaIMTdAGUIXs9aMPbRz1RKXXuKDGdDlyoNhziy21NI6wJiwQh8ul4mImZ3AzV\n" +
        "9kcleRwrscRhgVVBONcg6LVBhQKBgQC45+/SSC/Z8mlrhizzHfjm9bsb40o5Lz9b\n" +
        "DOTJF7y0o1FXaXMSSotKuEo8TE8PastMmcRmArtx69gcmESn+7VglMCOW6m554Jd\n" +
        "M3T7dEbU9Dl8WOciWphplOkGljOQco4HR9iEQttCDxMmlTyvuyYt0bsLBVy0K636\n" +
        "RiXrLcgFaQKBgFy1WhBsK67mn66M/of5Ur+aF23KwVPyPOV47kJCNyII3VfRzuuZ\n" +
        "EwJANq9thvIVwWwTDd0+wQWQULoolE/GJTYXi/w2c0xTca6bjNgmnISljo4bMgv6\n" +
        "O7FhXIeCCygjwNkvg4mNCpfJbaw0zr/DmID/UqYsMp45dvtet5nSfHW5AoGACD5/\n" +
        "GNcTGxqNzLd8xZIuiM2n/ARUSNxsbLjUcorWZQ9rDwSqlsQwFbLFzI5yb/OJAO9S\n" +
        "LGIuzVOAnTXEyeCVI6s+MpqvpJRH4bProVJ73f7NmVe1Zni3lu2Gvj5wKh6Rao2v\n" +
        "f6YjdHyLlArPW95yQ1S4jDM/AOF5rlD2W9f8tRECgYB4i3qu1eOUP8ND29qpiz3Z\n" +
        "kX0Kz8MJF/W8SI3EuWR06iOtnEQvUA19GGl+eP31+eeOLEDyJceGGGMHH42ERxq0\n" +
        "NLZaLd5FHebRvFwxbzD24nYBU8q/WawRmyG/u2TEGZ09jvtzX/XgkrxCFNFQpEoZ\n" +
        "DuIPM0H4W9l7v/kASh6DKQ==\n" +
        "-----END PRIVATE KEY-----";

    /// <summary>
    /// Generates a signed JWT token (RS256) with the given user ID, role, and optional additional
    /// claims. Matches the claim layout produced by MMCA.Common's <c>ITokenService.GenerateAccessToken</c>
    /// so downstream auth middleware sees the same shape regardless of whether the token came from a
    /// real <c>AuthenticationService</c> or from this test helper.
    /// </summary>
    /// <param name="audience">The token audience (must match the app's <c>Jwt:Audience</c>).</param>
    /// <param name="userId">The user identifier.</param>
    /// <param name="role">The user's role claim.</param>
    /// <param name="additionalClaims">Optional extra claims (e.g., <c>customer_id</c>, <c>speaker_id</c>, <c>email</c>, <c>name</c>).</param>
    /// <param name="privateKeyPem">PEM-encoded RSA private key. Defaults to <see cref="DefaultPrivateKeyPem"/>.</param>
    /// <param name="issuer">Token issuer claim. Defaults to <see cref="DefaultIssuer"/>.</param>
    /// <param name="keyId">JWT header <c>kid</c>. Defaults to <see cref="DefaultKeyId"/>.</param>
    /// <returns>A signed JWT string.</returns>
    public static string GenerateToken(
        string audience,
        UserIdentifierType userId,
        string role,
        IEnumerable<Claim>? additionalClaims = null,
        string? privateKeyPem = null,
        string issuer = DefaultIssuer,
        string keyId = DefaultKeyId)
    {
        // Import PEM → RSAParameters so the RSA instance can be safely disposed without
        // invalidating the key held by SigningCredentials.
        RSAParameters parameters;
        using (var rsa = RSA.Create())
        {
            rsa.ImportFromPem(privateKeyPem ?? DefaultPrivateKeyPem);
            parameters = rsa.ExportParameters(includePrivateParameters: true);
        }

        var key = new RsaSecurityKey(parameters) { KeyId = keyId };
        var credentials = new SigningCredentials(key, SecurityAlgorithms.RsaSha256);

        var claims = new List<Claim>
        {
            new(ClaimTypes.NameIdentifier, userId.ToString(CultureInfo.InvariantCulture)),
            new("user_id", userId.ToString(CultureInfo.InvariantCulture)),
            new(ClaimTypes.Role, role),
        };

        if (additionalClaims is not null)
        {
            claims.AddRange(additionalClaims);
        }

        var token = new JwtSecurityToken(
            issuer: issuer,
            audience: audience,
            claims: claims,
            expires: DateTime.UtcNow.AddHours(1),
            signingCredentials: credentials);

        return new JwtSecurityTokenHandler().WriteToken(token);
    }
}
