namespace MMCA.Common.Domain.Attributes;

/// <summary>
/// Marks an entity whose ID is auto-generated by the database (e.g., SQL Server IDENTITY).
/// Factory methods check this attribute at runtime via <c>Type.IsIdValueGenerated</c>
/// to decide whether to assign an explicit ID or leave it as <see langword="default"/> for the database to populate.
/// </summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class IdValueGeneratedAttribute : Attribute;
