using System.Security.Claims;
using AwesomeAssertions;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using MMCA.Common.Application.Interfaces;
using MMCA.Common.Application.Interfaces.Events;
using MMCA.Common.Application.Interfaces.Infrastructure.Auth;
using MMCA.Common.Application.Interfaces.Infrastructure.Persistence;
using MMCA.Common.Domain.Attributes;
using MMCA.Common.Domain.DomainEvents;
using MMCA.Common.Domain.Entities;
using MMCA.Common.Domain.Interfaces;
using MMCA.Common.Infrastructure.Persistence.Configuration.EntityTypeConfiguration;
using MMCA.Common.Infrastructure.Persistence.DataSources;
using MMCA.Common.Infrastructure.Persistence.DbContexts;
using MMCA.Common.Infrastructure.Persistence.DbContexts.Factory;
using MMCA.Common.Infrastructure.Persistence.Interceptors;
using MMCA.Common.Infrastructure.Persistence.Outbox;
using MMCA.Common.Infrastructure.Persistence.Outbox.Processing;
using MMCA.Common.Infrastructure.Persistence.Tenancy;
using Testcontainers.MsSql;

namespace MMCA.Common.Infrastructure.SQLServer.Tests;

/// <summary>
/// Exercises the shipped <see cref="SQLServerDbContext"/> and <see cref="DbContextFactory"/> against a
/// REAL SQL Server.
/// <para>
/// The unit tier mocks or substitutes the provider, so it cannot see three behaviours that only a
/// server has: <c>SET IDENTITY_INSERT</c> is SESSION state (it holds only on the connection that ran
/// it), a <c>rowversion</c> is generated by the server on every write, and the outbox row has to
/// reach the database in the same <c>SaveChanges</c> as the aggregate that raised the event.
/// </para>
/// <para>
/// These tests need a Docker daemon, so this project is outside <c>MMCA.Common.slnx</c> and runs in
/// its own CI job (<c>sqlserver-integration</c>).
/// </para>
/// </summary>
public sealed class SQLServerPersistenceTests : IAsyncLifetime
{
    // Same pinned 2022 CU tag the consumer-source-build job in ci.yml runs, so both SQL Server tiers
    // move together when the pin is bumped.
    private readonly MsSqlContainer _sqlServer = new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-CU27-ubuntu-22.04").Build();

    private ServiceProvider _serviceProvider = null!;
    private DataSourceResolver _resolver = null!;
    private EntityDataSourceRegistry _registry = null!;
    private PhysicalDbContextFactory _physicalFactory = null!;

    public async ValueTask InitializeAsync()
    {
        await _sqlServer.StartAsync();

        // The container's connection string points at master, where EnsureCreated would find
        // existing tables and create nothing; give the tier its own database.
        var connectionString = new SqlConnectionStringBuilder(_sqlServer.GetConnectionString())
        {
            InitialCatalog = "MmcaSqlServerTier",
        }.ConnectionString;

        var connectionStrings = new ConnectionStringSettings
        {
            SQLServerConnectionString = connectionString,
        };

        _resolver = new DataSourceResolver(
            Options.Create(connectionStrings),
            new DataSourcesSettings(),
            NullLogger<DataSourceResolver>.Instance);

        var assemblyProvider = new FixedAssemblyProvider();
        _registry = new EntityDataSourceRegistry(assemblyProvider, _resolver);

        _serviceProvider = new ServiceCollection()
            .AddSingleton(TimeProvider.System)
            .AddSingleton<ILoggerFactory, NullLoggerFactory>()
            .AddSingleton(typeof(ILogger<>), typeof(NullLogger<>))
            .AddSingleton<IDomainEventDispatcher, RecordingDomainEventDispatcher>()
            .AddSingleton<IOutboxSignal, OutboxSignal>()
            .AddSingleton<AuditSaveChangesInterceptor>()
            .AddSingleton<DomainEventSaveChangesInterceptor>()
            .AddSingleton<IEntityDataSourceRegistry>(_registry)
            .AddSingleton<IDataSourceResolver>(_resolver)
            .BuildServiceProvider();

        _physicalFactory = new PhysicalDbContextFactory(_serviceProvider, _resolver, assemblyProvider);

        await using var context = CreateContext();
        await context.Database.EnsureCreatedAsync();
    }

    public async ValueTask DisposeAsync()
    {
        if (_serviceProvider is not null)
        {
            await _serviceProvider.DisposeAsync();
        }

        await _sqlServer.DisposeAsync();
    }

    // T1. Assertion: through DbContextFactory's identity-insert save path, with NO ambient
    // transaction, saving an entity with an explicit int key on an identity column persists that
    // exact key value. SET IDENTITY_INSERT is session state, so this only holds if the SET and the
    // INSERT run on one session; without IDENTITY_INSERT the server rejects the explicit key outright.
    [Fact]
    public async Task IdentityInsert_WithoutAmbientTransaction_PersistsTheExplicitKey()
    {
        const int explicitId = 424_242;
        var code = NewCode();

        await using (var probe = CreateContext())
        {
            (await IsIdentityColumnAsync(probe)).Should().BeTrue(
                "the test is only meaningful if the key column really is an IDENTITY column");
        }

        await using (var factory = CreateFactory())
        {
            var context = factory.GetDbContext(DefaultKey());
            context.Database.CurrentTransaction.Should().BeNull("this path must work with no ambient transaction");

            context.Add(new SqlThing { Id = explicitId, Code = code });
            factory.RequestIdentityInsert();

            await factory.SaveChangesAsync(TestContext.Current.CancellationToken);
        }

        await using var reader = CreateContext();
        var saved = await reader.Set<SqlThing>().SingleAsync(t => t.Code == code, TestContext.Current.CancellationToken);

        saved.Id.Should().Be(explicitId, "an imported row keeps the key it was given, not one the identity column generated");
    }

    // T2. Assertion: a second save of a stale entity throws the provider's concurrency exception.
    // Both contexts load the same row version; the first save makes the server issue a new one, so
    // the second UPDATE's WHERE clause no longer matches and EF reports the conflict.
    [Fact]
    public async Task RowVersion_StaleSecondSave_ThrowsConcurrencyException()
    {
        var code = NewCode();

        await using (var seed = CreateContext())
        {
            seed.Add(new SqlThing { Id = default, Code = code });
            await seed.SaveChangesAsync(1, TestContext.Current.CancellationToken);
        }

        await using var first = CreateContext();
        await using var second = CreateContext();
        var fresh = await first.Set<SqlThing>().SingleAsync(t => t.Code == code, TestContext.Current.CancellationToken);
        var stale = await second.Set<SqlThing>().SingleAsync(t => t.Code == code, TestContext.Current.CancellationToken);

        stale.RowVersion.Should().NotBeEmpty("SQL Server generates the rowversion on insert");

        fresh.Label = "first writer";
        await first.SaveChangesAsync(1, TestContext.Current.CancellationToken);

        stale.Label = "second writer";
        var act = async () => await second.SaveChangesAsync(1, TestContext.Current.CancellationToken);

        await act.Should().ThrowAsync<DbUpdateConcurrencyException>(
            "the row version the second context loaded is no longer the one on the server");
    }

    // T3. Assertion: the outbox row is written in the same SaveChanges as the aggregate. One call,
    // two state entries written (the aggregate and its outbox row), and both rows present afterwards.
    // An integration event is used so no post-save dispatch touches the outbox row again.
    [Fact]
    public async Task OneSave_WritesTheAggregateAndItsOutboxRowTogether()
    {
        var code = NewCode();
        int written;

        await using (var context = CreateContext())
        {
            var thing = new SqlThing { Id = default, Code = code };
            thing.AddShippedEvent();
            context.Add(thing);
            written = await context.SaveChangesAsync(1, TestContext.Current.CancellationToken);
        }

        written.Should().Be(2, "the aggregate row and its outbox row are written by the same SaveChanges");

        await using var reader = CreateContext();
        (await reader.Set<SqlThing>().CountAsync(t => t.Code == code, TestContext.Current.CancellationToken))
            .Should().Be(1);
        (await reader.Set<OutboxMessage>().CountAsync(m => m.Payload.Contains(code), TestContext.Current.CancellationToken))
            .Should().Be(1, "exactly one outbox row carries the event raised on the saved aggregate");
    }

    private static string NewCode() => $"code-{Guid.NewGuid():N}";

    private DataSourceKey DefaultKey() => _resolver.ResolveLogical(DataSource.SQLServer, DataSourceKey.DefaultName);

    private ApplicationDbContext CreateContext() => _physicalFactory.Create(DefaultKey());

    private DbContextFactory CreateFactory() => new(
        _physicalFactory,
        _registry,
        _resolver,
        new FixedCurrentUserService(),
        new NoTenantContext(),
        Options.Create(new TenancySettings()));

    private static async Task<bool> IsIdentityColumnAsync(ApplicationDbContext context)
    {
        var entityType = context.Model.FindEntityType(typeof(SqlThing))!;
        var qualifiedTable = $"[{entityType.GetSchema() ?? "dbo"}].[{entityType.GetTableName()}]";

        var isIdentity = await context.Database
            .SqlQuery<int>($"SELECT CAST(COLUMNPROPERTY(OBJECT_ID({qualifiedTable}), 'Id', 'IsIdentity') AS int) AS [Value]")
            .SingleAsync(TestContext.Current.CancellationToken);

        return isIdentity == 1;
    }

    private sealed class FixedAssemblyProvider : IEntityConfigurationAssemblyProvider
    {
        public IReadOnlyList<System.Reflection.Assembly> GetConfigurationAssemblies() =>
            [typeof(SQLServerPersistenceTests).Assembly];
    }

    /// <summary>
    /// Stands in for the in-process dispatcher: the outbox routing only needs the call to succeed,
    /// and a handler of its own would test the dispatcher rather than the provider.
    /// </summary>
    private sealed class RecordingDomainEventDispatcher : IDomainEventDispatcher
    {
        public Task DispatchAsync(IEnumerable<IDomainEvent> domainEvents, CancellationToken cancellationToken = default)
            => Task.CompletedTask;
    }

    private sealed class FixedCurrentUserService : ICurrentUserService
    {
        public ClaimsPrincipal User { get; } = new(new ClaimsIdentity());

        public UserIdentifierType? UserId => 7;

        public string? Role => null;

        public T? GetClaimValue<T>(string claimType)
            where T : struct, IParsable<T> => null;
    }

    private sealed class NoTenantContext : ITenantContext
    {
        public string? TenantId => null;

        public bool IsResolved => false;

        public void SetTenant(string tenantId) => throw new NotSupportedException("This tier runs without tenancy.");
    }

    [IdValueGenerated]
    public sealed class SqlThing : AuditableAggregateRootEntity<int>
    {
        public string Code { get; set; } = string.Empty;

        public string? Label { get; set; }

        public void AddShippedEvent() => AddDomainEvent(new SqlThingShipped(Code));
    }

    public sealed record SqlThingShipped(string Code) : BaseDomainEvent, IIntegrationEvent;

    [UseDatabase("Default")]
    private sealed class SqlThingConfiguration : EntityTypeConfigurationSQLServer<SqlThing, int>
    {
        public override void Configure(EntityTypeBuilder<SqlThing> builder)
        {
            base.Configure(builder);

            builder.Property(p => p.Code).IsRequired().HasMaxLength(80);
            builder.Property(p => p.Label).HasMaxLength(80);
            builder.HasIndex(p => p.Code).IsUnique();
        }
    }
}
